openapi: 3.0.1
info:
  title: Documentación de la API de la Plantilla
  description: 'Aquí se encuentra la información correspondiente a los endpoints de 
    interacción con la API para facilitar el consumo de esta. (Esto es una plantilla para 
    representar el correcto funcionamiento del Swagger y actualmente no contiene ningun
    endpoint de la API, deberán agregarse cuando ya se encuentren disponibles).'
  termsOfService: http://swagger.io/terms/
  contact:
    email: encargado@salud.gob.sv
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore.swagger.io/v2
  - url: http://petstore.swagger.io/v2
paths:
  $include: "paths/paths.yaml"
components:
  schemas:
    $include: "schemas/schemas.yaml"
