## --------------------
## DON'T EDIT THIS FILE
## --------------------
## Engine: yamlinc@0.1.10
## Source: ./app/docs/swagger/include.yaml

openapi: 3.0.1
info:
  title: Documentación de la API de la Plantilla
  description: >-
    Aquí se encuentra la información correspondiente a los endpoints de 
    interacción con la API para facilitar el consumo de esta. (Esto es una
    plantilla para  representar el correcto funcionamiento del Swagger y
    actualmente no contiene ningun endpoint de la API, deberán agregarse cuando
    ya se encuentren disponibles).
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: encargado@salud.gob.sv
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: 'https://localhost:8000/api'
  - url: 'http://localhost:8000/api/v1'
paths:
  /usuario:
    post:
      tags:
        - usuario
      summary: Añade un nuevo usuario
      operationId: addUser
      requestBody:
        description: Objeto Usuario que será agregado al servicio
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
          application/xml:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      responses:
        '405':
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
    get:
      tags:
        - usuario
      summary: Muestra los usuarios almacenados
    put:
      tags:
        - usuario
      summary: Actualiza la información de un usuario
    delete:
      tags:
        - usuario
      summary: Elimina un usuario
    area: development
  /proveedor:
    get:
      tags:
        - proveedor
      summary: Muestra los proveedores
    post:
      tags:
        - proveedor
      summary: Añade un nuevo proveedor
    put:
      tags:
        - proveedor
      summary: Actualiza la información de un proveedor
    delete:
      tags:
        - proveedor
      summary: Elimina a un proveedor específico
    area: development
  /medico:
    get:
      tags:
        - medico
      summary: Muestra todos los medicos
    post:
      tags:
        - medico
      summary: Añade un medico
    put:
      tags:
        - medico
      summary: Actualiza la información de un medico
    delete:
      tags:
        - medico
      summary: Elimina a un medico
  /hospital:
    get:
      tags:
        - hospital
      summary: Muestra los Hospitales
    post:
      tags:
        - hospital
      summary: Añade un nuevo Hospital
    put:
      tags:
        - hospital
      summary: Actualiza la información de un Hospital
    delete:
      tags:
        - hospital
      summary: Elimina un Hospital
    area: api
components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          description: User Status
          format: int32
    Proveedor: {}
    Medico: {}
    Hospital: {}
