## --------------------
## DON'T EDIT THIS FILE
## --------------------
## Engine: yamlinc@0.1.10
## Source: ./app/docs/swagger/include.yaml

openapi: 3.0.1
info:
  title: Documentación de la API de la Plantilla
  description: >-
    Aquí se encuentra la información correspondiente a los endpoints de 
    interacción con la API para facilitar el consumo de esta. (Esto es una
    plantilla para  representar el correcto funcionamiento del Swagger y
    actualmente no contiene ningun endpoint de la API, deberán agregarse cuando
    ya se encuentren disponibles).
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: encargado@salud.gob.sv
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: 'https://petstore.swagger.io/v2'
  - url: 'http://petstore.swagger.io/v2'
paths:
  /usuario:
    post:
      tags:
        - usuario
      summary: Add a new pet to the store
      operationId: addPet
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
          application/xml:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      responses:
        '405':
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          description: User Status
          format: int32
