export const BitacoraCreateSchema={
    type:'object',
    properties:{
        id:{
            type:'number',
            required:true
        },
        id_usuario:{
            type:'number',
        },
        fecha_hora_reg:{
            type:'date-time',
        },
        ip_cliente:{
            type:'string',
        },
        ip_servidor:{
            type:'string',
        },
        metodo_http:{
            type:'string',
        },
        request_headers:{
            type:'string',
        },
        request_uri:{
            type:'string',
        },
        request_parameters:{
            type:'string',
        },
        request_content:{
            type:'string',
        },
        xrd_userid:{
            type:'string',
        },
        xrd_messageid:{
            type:'string',
        },
        xrd_client:{
            type:'string',
        },
        xrd_service:{
            type:'string',
        },
    }
}